name: Notificar a Teams

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje a Teams
        run: |
          curl -H 'Content-Type: application/json' \
            -d '{
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "summary": "GitHub Notificación",
              "themeColor": "0078D7",
              "title": "🚀 Push al repositorio",
              "text": "**${{ github.actor }}** hizo push al branch **${{ github.ref }}** en **${{ github.repository }}**"
            }' \
            ${{ secrets.TEAMS_WEBHOOK }}
